#! /bin/sh

#
#   Copyright 2015 Kai Huebl (kai@huebl-sgh.de)
#
#   Lizenziert gemäß Apache Licence Version 2.0 (die „Lizenz“); Nutzung dieser
#   Datei nur in Übereinstimmung mit der Lizenz erlaubt.
#   Eine Kopie der Lizenz erhalten Sie auf http://www.apache.org/licenses/LICENSE-2.0.
#
#   Sofern nicht gemäß geltendem Recht vorgeschrieben oder schriftlich vereinbart,
#   erfolgt die Bereitstellung der im Rahmen der Lizenz verbreiteten Software OHNE
#   GEWÄHR ODER VORBEHALTE – ganz gleich, ob ausdrücklich oder stillschweigend.
#
#   Informationen über die jeweiligen Bedingungen für Genehmigungen und Einschränkungen
#   im Rahmen der Lizenz finden Sie in der Lizenz.
#
#   Autor: Kai Huebl (kai@huebl-sgh.de)
#

echo "PRERM RUN"

if [ -x /sbin/stop ] && [ -e "/etc/init/OpcUaGui.conf" ]; then
    # use Ubuntu upstart
    echo "INFO: stopping daemon by upstart"
    /sbin/stop OpcUaGui 
elif [ -x /usr/bin/systemctl ] && [ -e "/usr/lib/systemd/system/OpcUaGui.service" ]; then
    # use systemd
    echo "INFO: stopping  daemon by systemd"
    /usr/bin/systemctl stop OpcUaGui.service
    /usr/bin/systemctl enable OpcUaGui.service
else
    # use SYSV init script
    if [ -e "/etc/init.d/OpcUaGui" ]; then
        echo "INFO: stopping daemon by SYS init script"
        invoke-rc.d OpcUaGui stop || exit $?
        update-rc.d -f OpcUaGui remove >/dev/null
    fi
fi

echo "PRERM RETURN"
exit 0

